development:
  # adapter: postgresql
  # encoding: unicode
  # database: defmetas
  # pool: 5
  # username: postgres
  # password: n3g@t!v0
  adapter: postgresql
  encoding: unicode
  database: defmetas
  pool: 5
  username: postgres
<<<<<<< HEAD
  password: n3g@t!v0
=======
  password: rootinfoway

>>>>>>> 05c1eb73f78153eb3e59e125399fc5ca240679aa
  host: 127.0.0.1
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: defmetas_test
  pool: 5
  username: postgres
  password: rootinfoway

production:
  adapter: postgresql
  encoding: unicode
  database: defmetas
  pool: 5
  username: defmetas
  password: defmetasinfoway
  host: 10.0.0.16
  port: 5432
